// automatically generated by the FlatBuffers compiler, do not modify
// Merged from: run_request.fbs, output_payload.fbs, run_request_result.fbs
// Regenerate with: just dart (from the flatbuffers directory)
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library gravio.acr;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

// Aliases for core types that are shadowed by FlatBuffers enum constants
typedef _String = String;
typedef _Map<K, V> = Map<K, V>;

// ── run_request.fbs ─────────────────────────────────────────────────────────

class TriggerType {
  final int value;
  const TriggerType._(this.value);

  factory TriggerType.fromValue(int value) {
    final result = values[value];
    if (result == null) {
        throw StateError('Invalid value $value for bit flag enum TriggerType');
    }
    return result;
  }

  static TriggerType? _createOrNull(int? value) =>
      value == null ? null : TriggerType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static bool containsValue(int value) => values.containsKey(value);

  static const TriggerType Event = TriggerType._(0);
  static const TriggerType Timer = TriggerType._(1);
  static const TriggerType InternalCall = TriggerType._(2);
  static const Map<int, TriggerType> values = {
    0: Event,
    1: Timer,
    2: InternalCall};

  static const fb.Reader<TriggerType> reader = _TriggerTypeReader();

  @override
  String toString() {
    return 'TriggerType{value: $value}';
  }
}

class _TriggerTypeReader extends fb.Reader<TriggerType> {
  const _TriggerTypeReader();

  @override
  int get size => 1;

  @override
  TriggerType read(fb.BufferContext bc, int offset) =>
      TriggerType.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class FlowType {
  final int value;
  const FlowType._(this.value);

  factory FlowType.fromValue(int value) {
    final result = values[value];
    if (result == null) {
        throw StateError('Invalid value $value for bit flag enum FlowType');
    }
    return result;
  }

  static FlowType? _createOrNull(int? value) =>
      value == null ? null : FlowType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 4;
  static bool containsValue(int value) => values.containsKey(value);

  static const FlowType None = FlowType._(0);
  static const FlowType Goto = FlowType._(1);
  static const FlowType Call = FlowType._(2);
  static const FlowType Jump = FlowType._(3);
  static const FlowType Parallel = FlowType._(4);
  static const Map<int, FlowType> values = {
    0: None,
    1: Goto,
    2: Call,
    3: Jump,
    4: Parallel};

  static const fb.Reader<FlowType> reader = _FlowTypeReader();

  @override
  String toString() {
    return 'FlowType{value: $value}';
  }
}

class _FlowTypeReader extends fb.Reader<FlowType> {
  const _FlowTypeReader();

  @override
  int get size => 1;

  @override
  FlowType read(fb.BufferContext bc, int offset) =>
      FlowType.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class HubkitDataType {
  final int value;
  const HubkitDataType._(this.value);

  factory HubkitDataType.fromValue(int value) {
    final result = values[value];
    if (result == null) {
        throw StateError('Invalid value $value for bit flag enum HubkitDataType');
    }
    return result;
  }

  static HubkitDataType? _createOrNull(int? value) =>
      value == null ? null : HubkitDataType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 5;
  static bool containsValue(int value) => values.containsKey(value);

  static const HubkitDataType Int = HubkitDataType._(0);
  static const HubkitDataType Double = HubkitDataType._(1);
  static const HubkitDataType Bool = HubkitDataType._(2);
  // ignore: non_constant_identifier_names
  static const HubkitDataType String = HubkitDataType._(3);
  static const HubkitDataType JSON = HubkitDataType._(4);
  static const HubkitDataType Binary = HubkitDataType._(5);
  static const _Map<int, HubkitDataType> values = {
    0: Int,
    1: Double,
    2: Bool,
    3: String,
    4: JSON,
    5: Binary};

  static const fb.Reader<HubkitDataType> reader = _HubkitDataTypeReader();

  @override
  _String toString() {
    return 'HubkitDataType{value: $value}';
  }
}

class _HubkitDataTypeReader extends fb.Reader<HubkitDataType> {
  const _HubkitDataTypeReader();

  @override
  int get size => 1;

  @override
  HubkitDataType read(fb.BufferContext bc, int offset) =>
      HubkitDataType.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class PropertyDataType {
  final int value;
  const PropertyDataType._(this.value);

  factory PropertyDataType.fromValue(int value) {
    final result = values[value];
    if (result == null) {
        throw StateError('Invalid value $value for bit flag enum PropertyDataType');
    }
    return result;
  }

  static PropertyDataType? _createOrNull(int? value) =>
      value == null ? null : PropertyDataType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 8;
  static bool containsValue(int value) => values.containsKey(value);

  // ignore: non_constant_identifier_names
  static const PropertyDataType Null = PropertyDataType._(0);
  // ignore: non_constant_identifier_names
  static const PropertyDataType String = PropertyDataType._(1);
  static const PropertyDataType Int = PropertyDataType._(2);
  static const PropertyDataType Double = PropertyDataType._(3);
  static const PropertyDataType Number = PropertyDataType._(4);
  static const PropertyDataType Bool = PropertyDataType._(5);
  static const PropertyDataType Byte = PropertyDataType._(6);
  // ignore: non_constant_identifier_names
  static const PropertyDataType List = PropertyDataType._(7);
  // ignore: non_constant_identifier_names
  static const PropertyDataType Map = PropertyDataType._(8);
  static const _Map<int, PropertyDataType> values = {
    0: Null,
    1: String,
    2: Int,
    3: Double,
    4: Number,
    5: Bool,
    6: Byte,
    7: List,
    8: Map};

  static const fb.Reader<PropertyDataType> reader = _PropertyDataTypeReader();

  @override
  _String toString() {
    return 'PropertyDataType{value: $value}';
  }
}

class _PropertyDataTypeReader extends fb.Reader<PropertyDataType> {
  const _PropertyDataTypeReader();

  @override
  int get size => 1;

  @override
  PropertyDataType read(fb.BufferContext bc, int offset) =>
      PropertyDataType.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class RunRequest {
  RunRequest._(this._bc, this._bcOffset);
  factory RunRequest(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<RunRequest> reader = _RunRequestReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get publisherId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get componentKind => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get componentId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  String? get executionId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  ProxyConfig? get proxyConfig => ProxyConfig.reader.vTableGetNullable(_bc, _bcOffset, 12);
  ResourceDirectories? get resourceDirectories => ResourceDirectories.reader.vTableGetNullable(_bc, _bcOffset, 14);
  ActionProperties? get actionProperties => ActionProperties.reader.vTableGetNullable(_bc, _bcOffset, 16);
  ///  ActionVariables are fully user-defined. Serialized as MsgPack.
  List<int>? get actionVariables => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 18);
  ///  TriggerProperties are fully user-defined. Serialized as MsgPack.
  List<int>? get triggerProperties => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 20);
  TriggerVariables? get triggerVariables => TriggerVariables.reader.vTableGetNullable(_bc, _bcOffset, 22);
  ///  ComponentProperties are mostly user-defined, but with addon-components, cannot be known before compilation time. Serialized as MsgPack.
  List<int>? get componentProperties => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 24);
  RunComponentPayload? get inputPayload => RunComponentPayload.reader.vTableGetNullable(_bc, _bcOffset, 26);

  @override
  String toString() {
    return 'RunRequest{publisherId: $publisherId, componentKind: $componentKind, componentId: $componentId, executionId: $executionId, proxyConfig: $proxyConfig, resourceDirectories: $resourceDirectories, actionProperties: $actionProperties, actionVariables: $actionVariables, triggerProperties: $triggerProperties, triggerVariables: $triggerVariables, componentProperties: $componentProperties, inputPayload: $inputPayload}';
  }
}

class _RunRequestReader extends fb.TableReader<RunRequest> {
  const _RunRequestReader();

  @override
  RunRequest createObject(fb.BufferContext bc, int offset) =>
    RunRequest._(bc, offset);
}

class RunRequestBuilder {
  RunRequestBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(12);
  }

  int addPublisherIdOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addComponentKindOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addComponentIdOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addExecutionIdOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addProxyConfigOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addResourceDirectoriesOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addActionPropertiesOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addActionVariablesOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addTriggerPropertiesOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addTriggerVariablesOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addComponentPropertiesOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addInputPayloadOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class RunRequestObjectBuilder extends fb.ObjectBuilder {
  final String? _publisherId;
  final String? _componentKind;
  final String? _componentId;
  final String? _executionId;
  final ProxyConfigObjectBuilder? _proxyConfig;
  final ResourceDirectoriesObjectBuilder? _resourceDirectories;
  final ActionPropertiesObjectBuilder? _actionProperties;
  final List<int>? _actionVariables;
  final List<int>? _triggerProperties;
  final TriggerVariablesObjectBuilder? _triggerVariables;
  final List<int>? _componentProperties;
  final RunComponentPayloadObjectBuilder? _inputPayload;

  RunRequestObjectBuilder({
    String? publisherId,
    String? componentKind,
    String? componentId,
    String? executionId,
    ProxyConfigObjectBuilder? proxyConfig,
    ResourceDirectoriesObjectBuilder? resourceDirectories,
    ActionPropertiesObjectBuilder? actionProperties,
    List<int>? actionVariables,
    List<int>? triggerProperties,
    TriggerVariablesObjectBuilder? triggerVariables,
    List<int>? componentProperties,
    RunComponentPayloadObjectBuilder? inputPayload,
  })
      : _publisherId = publisherId,
        _componentKind = componentKind,
        _componentId = componentId,
        _executionId = executionId,
        _proxyConfig = proxyConfig,
        _resourceDirectories = resourceDirectories,
        _actionProperties = actionProperties,
        _actionVariables = actionVariables,
        _triggerProperties = triggerProperties,
        _triggerVariables = triggerVariables,
        _componentProperties = componentProperties,
        _inputPayload = inputPayload;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? publisherIdOffset = _publisherId == null ? null
        : fbBuilder.writeString(_publisherId!);
    final int? componentKindOffset = _componentKind == null ? null
        : fbBuilder.writeString(_componentKind!);
    final int? componentIdOffset = _componentId == null ? null
        : fbBuilder.writeString(_componentId!);
    final int? executionIdOffset = _executionId == null ? null
        : fbBuilder.writeString(_executionId!);
    final int? proxyConfigOffset = _proxyConfig?.getOrCreateOffset(fbBuilder);
    final int? resourceDirectoriesOffset = _resourceDirectories?.getOrCreateOffset(fbBuilder);
    final int? actionPropertiesOffset = _actionProperties?.getOrCreateOffset(fbBuilder);
    final int? actionVariablesOffset = _actionVariables == null ? null
        : fbBuilder.writeListUint8(_actionVariables!);
    final int? triggerPropertiesOffset = _triggerProperties == null ? null
        : fbBuilder.writeListUint8(_triggerProperties!);
    final int? triggerVariablesOffset = _triggerVariables?.getOrCreateOffset(fbBuilder);
    final int? componentPropertiesOffset = _componentProperties == null ? null
        : fbBuilder.writeListUint8(_componentProperties!);
    final int? inputPayloadOffset = _inputPayload?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(12);
    fbBuilder.addOffset(0, publisherIdOffset);
    fbBuilder.addOffset(1, componentKindOffset);
    fbBuilder.addOffset(2, componentIdOffset);
    fbBuilder.addOffset(3, executionIdOffset);
    fbBuilder.addOffset(4, proxyConfigOffset);
    fbBuilder.addOffset(5, resourceDirectoriesOffset);
    fbBuilder.addOffset(6, actionPropertiesOffset);
    fbBuilder.addOffset(7, actionVariablesOffset);
    fbBuilder.addOffset(8, triggerPropertiesOffset);
    fbBuilder.addOffset(9, triggerVariablesOffset);
    fbBuilder.addOffset(10, componentPropertiesOffset);
    fbBuilder.addOffset(11, inputPayloadOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ActionProperties {
  ActionProperties._(this._bc, this._bcOffset);
  factory ActionProperties(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ActionProperties> reader = _ActionPropertiesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get timeout => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  ///  Handles overflow of any items that aren't defined above. Serialized as MsgPack.
  List<int>? get extra => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'ActionProperties{timeout: $timeout, extra: $extra}';
  }
}

class _ActionPropertiesReader extends fb.TableReader<ActionProperties> {
  const _ActionPropertiesReader();

  @override
  ActionProperties createObject(fb.BufferContext bc, int offset) =>
    ActionProperties._(bc, offset);
}

class ActionPropertiesBuilder {
  ActionPropertiesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addTimeout(int? timeout) {
    fbBuilder.addInt32(0, timeout);
    return fbBuilder.offset;
  }
  int addExtraOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ActionPropertiesObjectBuilder extends fb.ObjectBuilder {
  final int? _timeout;
  final List<int>? _extra;

  ActionPropertiesObjectBuilder({
    int? timeout,
    List<int>? extra,
  })
      : _timeout = timeout,
        _extra = extra;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? extraOffset = _extra == null ? null
        : fbBuilder.writeListUint8(_extra!);
    fbBuilder.startTable(2);
    fbBuilder.addInt32(0, _timeout);
    fbBuilder.addOffset(1, extraOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class TriggerVariables {
  TriggerVariables._(this._bc, this._bcOffset);
  factory TriggerVariables(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<TriggerVariables> reader = _TriggerVariablesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  TriggerType get triggerType => TriggerType.fromValue(const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0));
  String? get timestamp => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get areaId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  String? get layerId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  String? get dataKindId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 12);
  String? get virtualDeviceId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 14);
  String? get physicalDeviceId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 16);
  String? get dataId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 18);
  String? get areaName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 20);
  String? get layerName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 22);
  String? get kindName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 24);
  String? get virtualDeviceName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 26);
  String? get physicalDeviceName => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 28);
  HubkitDataType get dataType => HubkitDataType.fromValue(const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 30, 0));
  ///  Handles overflow of any items that aren't defined above. Serialized as MsgPack.
  List<int>? get extra => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 32);

  @override
  String toString() {
    return 'TriggerVariables{triggerType: $triggerType, timestamp: $timestamp, areaId: $areaId, layerId: $layerId, dataKindId: $dataKindId, virtualDeviceId: $virtualDeviceId, physicalDeviceId: $physicalDeviceId, dataId: $dataId, areaName: $areaName, layerName: $layerName, kindName: $kindName, virtualDeviceName: $virtualDeviceName, physicalDeviceName: $physicalDeviceName, dataType: $dataType, extra: $extra}';
  }
}

class _TriggerVariablesReader extends fb.TableReader<TriggerVariables> {
  const _TriggerVariablesReader();

  @override
  TriggerVariables createObject(fb.BufferContext bc, int offset) =>
    TriggerVariables._(bc, offset);
}

class TriggerVariablesBuilder {
  TriggerVariablesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(15);
  }

  int addTriggerType(TriggerType? triggerType) {
    fbBuilder.addUint8(0, triggerType?.value);
    return fbBuilder.offset;
  }
  int addTimestampOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addAreaIdOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addLayerIdOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addDataKindIdOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addVirtualDeviceIdOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addPhysicalDeviceIdOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addDataIdOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addAreaNameOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addLayerNameOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addKindNameOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addVirtualDeviceNameOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }
  int addPhysicalDeviceNameOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }
  int addDataType(HubkitDataType? dataType) {
    fbBuilder.addUint8(13, dataType?.value);
    return fbBuilder.offset;
  }
  int addExtraOffset(int? offset) {
    fbBuilder.addOffset(14, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TriggerVariablesObjectBuilder extends fb.ObjectBuilder {
  final TriggerType? _triggerType;
  final String? _timestamp;
  final String? _areaId;
  final String? _layerId;
  final String? _dataKindId;
  final String? _virtualDeviceId;
  final String? _physicalDeviceId;
  final String? _dataId;
  final String? _areaName;
  final String? _layerName;
  final String? _kindName;
  final String? _virtualDeviceName;
  final String? _physicalDeviceName;
  final HubkitDataType? _dataType;
  final List<int>? _extra;

  TriggerVariablesObjectBuilder({
    TriggerType? triggerType,
    String? timestamp,
    String? areaId,
    String? layerId,
    String? dataKindId,
    String? virtualDeviceId,
    String? physicalDeviceId,
    String? dataId,
    String? areaName,
    String? layerName,
    String? kindName,
    String? virtualDeviceName,
    String? physicalDeviceName,
    HubkitDataType? dataType,
    List<int>? extra,
  })
      : _triggerType = triggerType,
        _timestamp = timestamp,
        _areaId = areaId,
        _layerId = layerId,
        _dataKindId = dataKindId,
        _virtualDeviceId = virtualDeviceId,
        _physicalDeviceId = physicalDeviceId,
        _dataId = dataId,
        _areaName = areaName,
        _layerName = layerName,
        _kindName = kindName,
        _virtualDeviceName = virtualDeviceName,
        _physicalDeviceName = physicalDeviceName,
        _dataType = dataType,
        _extra = extra;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? timestampOffset = _timestamp == null ? null
        : fbBuilder.writeString(_timestamp!);
    final int? areaIdOffset = _areaId == null ? null
        : fbBuilder.writeString(_areaId!);
    final int? layerIdOffset = _layerId == null ? null
        : fbBuilder.writeString(_layerId!);
    final int? dataKindIdOffset = _dataKindId == null ? null
        : fbBuilder.writeString(_dataKindId!);
    final int? virtualDeviceIdOffset = _virtualDeviceId == null ? null
        : fbBuilder.writeString(_virtualDeviceId!);
    final int? physicalDeviceIdOffset = _physicalDeviceId == null ? null
        : fbBuilder.writeString(_physicalDeviceId!);
    final int? dataIdOffset = _dataId == null ? null
        : fbBuilder.writeString(_dataId!);
    final int? areaNameOffset = _areaName == null ? null
        : fbBuilder.writeString(_areaName!);
    final int? layerNameOffset = _layerName == null ? null
        : fbBuilder.writeString(_layerName!);
    final int? kindNameOffset = _kindName == null ? null
        : fbBuilder.writeString(_kindName!);
    final int? virtualDeviceNameOffset = _virtualDeviceName == null ? null
        : fbBuilder.writeString(_virtualDeviceName!);
    final int? physicalDeviceNameOffset = _physicalDeviceName == null ? null
        : fbBuilder.writeString(_physicalDeviceName!);
    final int? extraOffset = _extra == null ? null
        : fbBuilder.writeListUint8(_extra!);
    fbBuilder.startTable(15);
    fbBuilder.addUint8(0, _triggerType?.value);
    fbBuilder.addOffset(1, timestampOffset);
    fbBuilder.addOffset(2, areaIdOffset);
    fbBuilder.addOffset(3, layerIdOffset);
    fbBuilder.addOffset(4, dataKindIdOffset);
    fbBuilder.addOffset(5, virtualDeviceIdOffset);
    fbBuilder.addOffset(6, physicalDeviceIdOffset);
    fbBuilder.addOffset(7, dataIdOffset);
    fbBuilder.addOffset(8, areaNameOffset);
    fbBuilder.addOffset(9, layerNameOffset);
    fbBuilder.addOffset(10, kindNameOffset);
    fbBuilder.addOffset(11, virtualDeviceNameOffset);
    fbBuilder.addOffset(12, physicalDeviceNameOffset);
    fbBuilder.addUint8(13, _dataType?.value);
    fbBuilder.addOffset(14, extraOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ComponentVariables {
  ComponentVariables._(this._bc, this._bcOffset);
  factory ComponentVariables(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ComponentVariables> reader = _ComponentVariablesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  ///  User- and Component- defined. Serialized as MsgPack.
  List<int>? get payload => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 4);
  ///  anything else that users may put on the component, including temp variables in the mappings, etc. Serialized as MsgPack.
  List<int>? get extra => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'ComponentVariables{payload: $payload, extra: $extra}';
  }
}

class _ComponentVariablesReader extends fb.TableReader<ComponentVariables> {
  const _ComponentVariablesReader();

  @override
  ComponentVariables createObject(fb.BufferContext bc, int offset) =>
    ComponentVariables._(bc, offset);
}

class ComponentVariablesBuilder {
  ComponentVariablesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addPayloadOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addExtraOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ComponentVariablesObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _payload;
  final List<int>? _extra;

  ComponentVariablesObjectBuilder({
    List<int>? payload,
    List<int>? extra,
  })
      : _payload = payload,
        _extra = extra;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? payloadOffset = _payload == null ? null
        : fbBuilder.writeListUint8(_payload!);
    final int? extraOffset = _extra == null ? null
        : fbBuilder.writeListUint8(_extra!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, payloadOffset);
    fbBuilder.addOffset(1, extraOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class RunComponentPayload {
  RunComponentPayload._(this._bc, this._bcOffset);
  factory RunComponentPayload(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<RunComponentPayload> reader = _RunComponentPayloadReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get flowId => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  FlowType get flowType => FlowType.fromValue(const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 0));
  ComponentVariables? get componentVariables => ComponentVariables.reader.vTableGetNullable(_bc, _bcOffset, 8);
  List<int>? get outputVariables => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 10);
  PropertyDataType2? get bodyDataType => PropertyDataType2.reader.vTableGetNullable(_bc, _bcOffset, 12);

  @override
  String toString() {
    return 'RunComponentPayload{flowId: $flowId, flowType: $flowType, componentVariables: $componentVariables, outputVariables: $outputVariables, bodyDataType: $bodyDataType}';
  }
}

class _RunComponentPayloadReader extends fb.TableReader<RunComponentPayload> {
  const _RunComponentPayloadReader();

  @override
  RunComponentPayload createObject(fb.BufferContext bc, int offset) =>
    RunComponentPayload._(bc, offset);
}

class RunComponentPayloadBuilder {
  RunComponentPayloadBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addFlowIdOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addFlowType(FlowType? flowType) {
    fbBuilder.addUint8(1, flowType?.value);
    return fbBuilder.offset;
  }
  int addComponentVariablesOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addOutputVariablesOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addBodyDataTypeOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class RunComponentPayloadObjectBuilder extends fb.ObjectBuilder {
  final String? _flowId;
  final FlowType? _flowType;
  final ComponentVariablesObjectBuilder? _componentVariables;
  final List<int>? _outputVariables;
  final PropertyDataType2ObjectBuilder? _bodyDataType;

  RunComponentPayloadObjectBuilder({
    String? flowId,
    FlowType? flowType,
    ComponentVariablesObjectBuilder? componentVariables,
    List<int>? outputVariables,
    PropertyDataType2ObjectBuilder? bodyDataType,
  })
      : _flowId = flowId,
        _flowType = flowType,
        _componentVariables = componentVariables,
        _outputVariables = outputVariables,
        _bodyDataType = bodyDataType;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? flowIdOffset = _flowId == null ? null
        : fbBuilder.writeString(_flowId!);
    final int? componentVariablesOffset = _componentVariables?.getOrCreateOffset(fbBuilder);
    final int? outputVariablesOffset = _outputVariables == null ? null
        : fbBuilder.writeListUint8(_outputVariables!);
    final int? bodyDataTypeOffset = _bodyDataType?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(5);
    fbBuilder.addOffset(0, flowIdOffset);
    fbBuilder.addUint8(1, _flowType?.value);
    fbBuilder.addOffset(2, componentVariablesOffset);
    fbBuilder.addOffset(3, outputVariablesOffset);
    fbBuilder.addOffset(4, bodyDataTypeOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class PropertyDataType2 {
  PropertyDataType2._(this._bc, this._bcOffset);
  factory PropertyDataType2(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<PropertyDataType2> reader = _PropertyDataType2Reader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  PropertyDataType get underlyingType => PropertyDataType.fromValue(const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0));
  PropertyDataType2? get genericTypeParameter1 => PropertyDataType2.reader.vTableGetNullable(_bc, _bcOffset, 6);
  PropertyDataType2? get genericTypeParameter2 => PropertyDataType2.reader.vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'PropertyDataType2{underlyingType: $underlyingType, genericTypeParameter1: $genericTypeParameter1, genericTypeParameter2: $genericTypeParameter2}';
  }
}

class _PropertyDataType2Reader extends fb.TableReader<PropertyDataType2> {
  const _PropertyDataType2Reader();

  @override
  PropertyDataType2 createObject(fb.BufferContext bc, int offset) =>
    PropertyDataType2._(bc, offset);
}

class PropertyDataType2Builder {
  PropertyDataType2Builder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addUnderlyingType(PropertyDataType? underlyingType) {
    fbBuilder.addUint8(0, underlyingType?.value);
    return fbBuilder.offset;
  }
  int addGenericTypeParameter1Offset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addGenericTypeParameter2Offset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PropertyDataType2ObjectBuilder extends fb.ObjectBuilder {
  final PropertyDataType? _underlyingType;
  final PropertyDataType2ObjectBuilder? _genericTypeParameter1;
  final PropertyDataType2ObjectBuilder? _genericTypeParameter2;

  PropertyDataType2ObjectBuilder({
    PropertyDataType? underlyingType,
    PropertyDataType2ObjectBuilder? genericTypeParameter1,
    PropertyDataType2ObjectBuilder? genericTypeParameter2,
  })
      : _underlyingType = underlyingType,
        _genericTypeParameter1 = genericTypeParameter1,
        _genericTypeParameter2 = genericTypeParameter2;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? genericTypeParameter1Offset = _genericTypeParameter1?.getOrCreateOffset(fbBuilder);
    final int? genericTypeParameter2Offset = _genericTypeParameter2?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addUint8(0, _underlyingType?.value);
    fbBuilder.addOffset(1, genericTypeParameter1Offset);
    fbBuilder.addOffset(2, genericTypeParameter2Offset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ProxyConfig {
  ProxyConfig._(this._bc, this._bcOffset);
  factory ProxyConfig(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ProxyConfig> reader = _ProxyConfigReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  bool get isHttpEnabled => const fb.BoolReader().vTableGet(_bc, _bcOffset, 4, false);
  String? get httpUrl => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get httpUsername => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  String? get httpPassword => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  bool get isHttpsEnabled => const fb.BoolReader().vTableGet(_bc, _bcOffset, 12, false);
  String? get httpsUrl => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 14);
  String? get httpsUsername => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 16);
  String? get httpsPassword => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 18);
  String? get noProxy => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 20);

  @override
  String toString() {
    return 'ProxyConfig{isHttpEnabled: $isHttpEnabled, httpUrl: $httpUrl, httpUsername: $httpUsername, httpPassword: $httpPassword, isHttpsEnabled: $isHttpsEnabled, httpsUrl: $httpsUrl, httpsUsername: $httpsUsername, httpsPassword: $httpsPassword, noProxy: $noProxy}';
  }
}

class _ProxyConfigReader extends fb.TableReader<ProxyConfig> {
  const _ProxyConfigReader();

  @override
  ProxyConfig createObject(fb.BufferContext bc, int offset) =>
    ProxyConfig._(bc, offset);
}

class ProxyConfigBuilder {
  ProxyConfigBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(9);
  }

  int addIsHttpEnabled(bool? isHttpEnabled) {
    fbBuilder.addBool(0, isHttpEnabled);
    return fbBuilder.offset;
  }
  int addHttpUrlOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addHttpUsernameOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addHttpPasswordOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addIsHttpsEnabled(bool? isHttpsEnabled) {
    fbBuilder.addBool(4, isHttpsEnabled);
    return fbBuilder.offset;
  }
  int addHttpsUrlOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addHttpsUsernameOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addHttpsPasswordOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addNoProxyOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ProxyConfigObjectBuilder extends fb.ObjectBuilder {
  final bool? _isHttpEnabled;
  final String? _httpUrl;
  final String? _httpUsername;
  final String? _httpPassword;
  final bool? _isHttpsEnabled;
  final String? _httpsUrl;
  final String? _httpsUsername;
  final String? _httpsPassword;
  final String? _noProxy;

  ProxyConfigObjectBuilder({
    bool? isHttpEnabled,
    String? httpUrl,
    String? httpUsername,
    String? httpPassword,
    bool? isHttpsEnabled,
    String? httpsUrl,
    String? httpsUsername,
    String? httpsPassword,
    String? noProxy,
  })
      : _isHttpEnabled = isHttpEnabled,
        _httpUrl = httpUrl,
        _httpUsername = httpUsername,
        _httpPassword = httpPassword,
        _isHttpsEnabled = isHttpsEnabled,
        _httpsUrl = httpsUrl,
        _httpsUsername = httpsUsername,
        _httpsPassword = httpsPassword,
        _noProxy = noProxy;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? httpUrlOffset = _httpUrl == null ? null
        : fbBuilder.writeString(_httpUrl!);
    final int? httpUsernameOffset = _httpUsername == null ? null
        : fbBuilder.writeString(_httpUsername!);
    final int? httpPasswordOffset = _httpPassword == null ? null
        : fbBuilder.writeString(_httpPassword!);
    final int? httpsUrlOffset = _httpsUrl == null ? null
        : fbBuilder.writeString(_httpsUrl!);
    final int? httpsUsernameOffset = _httpsUsername == null ? null
        : fbBuilder.writeString(_httpsUsername!);
    final int? httpsPasswordOffset = _httpsPassword == null ? null
        : fbBuilder.writeString(_httpsPassword!);
    final int? noProxyOffset = _noProxy == null ? null
        : fbBuilder.writeString(_noProxy!);
    fbBuilder.startTable(9);
    fbBuilder.addBool(0, _isHttpEnabled);
    fbBuilder.addOffset(1, httpUrlOffset);
    fbBuilder.addOffset(2, httpUsernameOffset);
    fbBuilder.addOffset(3, httpPasswordOffset);
    fbBuilder.addBool(4, _isHttpsEnabled);
    fbBuilder.addOffset(5, httpsUrlOffset);
    fbBuilder.addOffset(6, httpsUsernameOffset);
    fbBuilder.addOffset(7, httpsPasswordOffset);
    fbBuilder.addOffset(8, noProxyOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ResourceDirectories {
  ResourceDirectories._(this._bc, this._bcOffset);
  factory ResourceDirectories(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ResourceDirectories> reader = _ResourceDirectoriesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  DirectoryPermissions? get owned => DirectoryPermissions.reader.vTableGetNullable(_bc, _bcOffset, 4);
  DirectoryPermissions? get shared => DirectoryPermissions.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'ResourceDirectories{owned: $owned, shared: $shared}';
  }
}

class _ResourceDirectoriesReader extends fb.TableReader<ResourceDirectories> {
  const _ResourceDirectoriesReader();

  @override
  ResourceDirectories createObject(fb.BufferContext bc, int offset) =>
    ResourceDirectories._(bc, offset);
}

class ResourceDirectoriesBuilder {
  ResourceDirectoriesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addOwnedOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addSharedOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ResourceDirectoriesObjectBuilder extends fb.ObjectBuilder {
  final DirectoryPermissionsObjectBuilder? _owned;
  final DirectoryPermissionsObjectBuilder? _shared;

  ResourceDirectoriesObjectBuilder({
    DirectoryPermissionsObjectBuilder? owned,
    DirectoryPermissionsObjectBuilder? shared,
  })
      : _owned = owned,
        _shared = shared;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? ownedOffset = _owned?.getOrCreateOffset(fbBuilder);
    final int? sharedOffset = _shared?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, ownedOffset);
    fbBuilder.addOffset(1, sharedOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class DirectoryPermissions {
  DirectoryPermissions._(this._bc, this._bcOffset);
  factory DirectoryPermissions(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<DirectoryPermissions> reader = _DirectoryPermissionsReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get relativeLocation => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  bool get canRead => const fb.BoolReader().vTableGet(_bc, _bcOffset, 6, false);
  bool get canWrite => const fb.BoolReader().vTableGet(_bc, _bcOffset, 8, false);
  bool get canExecute => const fb.BoolReader().vTableGet(_bc, _bcOffset, 10, false);

  @override
  String toString() {
    return 'DirectoryPermissions{relativeLocation: $relativeLocation, canRead: $canRead, canWrite: $canWrite, canExecute: $canExecute}';
  }
}

class _DirectoryPermissionsReader extends fb.TableReader<DirectoryPermissions> {
  const _DirectoryPermissionsReader();

  @override
  DirectoryPermissions createObject(fb.BufferContext bc, int offset) =>
    DirectoryPermissions._(bc, offset);
}

class DirectoryPermissionsBuilder {
  DirectoryPermissionsBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addRelativeLocationOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addCanRead(bool? canRead) {
    fbBuilder.addBool(1, canRead);
    return fbBuilder.offset;
  }
  int addCanWrite(bool? canWrite) {
    fbBuilder.addBool(2, canWrite);
    return fbBuilder.offset;
  }
  int addCanExecute(bool? canExecute) {
    fbBuilder.addBool(3, canExecute);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class DirectoryPermissionsObjectBuilder extends fb.ObjectBuilder {
  final String? _relativeLocation;
  final bool? _canRead;
  final bool? _canWrite;
  final bool? _canExecute;

  DirectoryPermissionsObjectBuilder({
    String? relativeLocation,
    bool? canRead,
    bool? canWrite,
    bool? canExecute,
  })
      : _relativeLocation = relativeLocation,
        _canRead = canRead,
        _canWrite = canWrite,
        _canExecute = canExecute;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? relativeLocationOffset = _relativeLocation == null ? null
        : fbBuilder.writeString(_relativeLocation!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, relativeLocationOffset);
    fbBuilder.addBool(1, _canRead);
    fbBuilder.addBool(2, _canWrite);
    fbBuilder.addBool(3, _canExecute);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

// ── output_payload.fbs ──────────────────────────────────────────────────────

class OutputPayload {
  OutputPayload._(this._bc, this._bcOffset);
  factory OutputPayload(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<OutputPayload> reader = _OutputPayloadReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  ///  User- and Component- defined. Serialized as MsgPack.
  List<int>? get payload => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 4);
  ///  Dedicated output variables (cv) of this components
  List<int>? get outputVariables => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'OutputPayload{payload: $payload, outputVariables: $outputVariables}';
  }
}

class _OutputPayloadReader extends fb.TableReader<OutputPayload> {
  const _OutputPayloadReader();

  @override
  OutputPayload createObject(fb.BufferContext bc, int offset) =>
    OutputPayload._(bc, offset);
}

class OutputPayloadBuilder {
  OutputPayloadBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addPayloadOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addOutputVariablesOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class OutputPayloadObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _payload;
  final List<int>? _outputVariables;

  OutputPayloadObjectBuilder({
    List<int>? payload,
    List<int>? outputVariables,
  })
      : _payload = payload,
        _outputVariables = outputVariables;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? payloadOffset = _payload == null ? null
        : fbBuilder.writeListUint8(_payload!);
    final int? outputVariablesOffset = _outputVariables == null ? null
        : fbBuilder.writeListUint8(_outputVariables!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, payloadOffset);
    fbBuilder.addOffset(1, outputVariablesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

// ── run_request_result.fbs ──────────────────────────────────────────────────

class ComponentRunResult {
  final int value;
  const ComponentRunResult._(this.value);

  factory ComponentRunResult.fromValue(int value) {
    final result = values[value];
    if (result == null) {
        throw StateError('Invalid value $value for bit flag enum ComponentRunResult');
    }
    return result;
  }

  static ComponentRunResult? _createOrNull(int? value) =>
      value == null ? null : ComponentRunResult.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 3;
  static bool containsValue(int value) => values.containsKey(value);

  static const ComponentRunResult Finished = ComponentRunResult._(0);
  static const ComponentRunResult Error = ComponentRunResult._(1);
  static const ComponentRunResult Canceled = ComponentRunResult._(2);
  static const ComponentRunResult Timedout = ComponentRunResult._(3);
  static const Map<int, ComponentRunResult> values = {
    0: Finished,
    1: Error,
    2: Canceled,
    3: Timedout};

  static const fb.Reader<ComponentRunResult> reader = _ComponentRunResultReader();

  @override
  String toString() {
    return 'ComponentRunResult{value: $value}';
  }
}

class _ComponentRunResultReader extends fb.Reader<ComponentRunResult> {
  const _ComponentRunResultReader();

  @override
  int get size => 1;

  @override
  ComponentRunResult read(fb.BufferContext bc, int offset) =>
      ComponentRunResult.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class PostError {
  PostError._(this._bc, this._bcOffset);
  factory PostError(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<PostError> reader = _PostErrorReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get code => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get message => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'PostError{code: $code, message: $message}';
  }
}

class _PostErrorReader extends fb.TableReader<PostError> {
  const _PostErrorReader();

  @override
  PostError createObject(fb.BufferContext bc, int offset) =>
    PostError._(bc, offset);
}

class PostErrorBuilder {
  PostErrorBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addCodeOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addMessageOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PostErrorObjectBuilder extends fb.ObjectBuilder {
  final String? _code;
  final String? _message;

  PostErrorObjectBuilder({
    String? code,
    String? message,
  })
      : _code = code,
        _message = message;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? codeOffset = _code == null ? null
        : fbBuilder.writeString(_code!);
    final int? messageOffset = _message == null ? null
        : fbBuilder.writeString(_message!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, codeOffset);
    fbBuilder.addOffset(1, messageOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ComponentResult {
  ComponentResult._(this._bc, this._bcOffset);
  factory ComponentResult(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ComponentResult> reader = _ComponentResultReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  ComponentRunResult get componentRunResult => ComponentRunResult.fromValue(const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0));
  List<int>? get payload => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);
  PostError? get postError => PostError.reader.vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'ComponentResult{componentRunResult: $componentRunResult, payload: $payload, postError: $postError}';
  }
}

class _ComponentResultReader extends fb.TableReader<ComponentResult> {
  const _ComponentResultReader();

  @override
  ComponentResult createObject(fb.BufferContext bc, int offset) =>
    ComponentResult._(bc, offset);
}

class ComponentResultBuilder {
  ComponentResultBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addComponentRunResult(ComponentRunResult? componentRunResult) {
    fbBuilder.addUint8(0, componentRunResult?.value);
    return fbBuilder.offset;
  }
  int addPayloadOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addPostErrorOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ComponentResultObjectBuilder extends fb.ObjectBuilder {
  final ComponentRunResult? _componentRunResult;
  final List<int>? _payload;
  final PostErrorObjectBuilder? _postError;

  ComponentResultObjectBuilder({
    ComponentRunResult? componentRunResult,
    List<int>? payload,
    PostErrorObjectBuilder? postError,
  })
      : _componentRunResult = componentRunResult,
        _payload = payload,
        _postError = postError;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? payloadOffset = _payload == null ? null
        : fbBuilder.writeListUint8(_payload!);
    final int? postErrorOffset = _postError?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addUint8(0, _componentRunResult?.value);
    fbBuilder.addOffset(1, payloadOffset);
    fbBuilder.addOffset(2, postErrorOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
